pipeline {
    environment {
            MAVEN_HOME = tool('docker')
            PATH = ${DOCKER_HOME}:${env.PATH}
        }
        docker {
            image 'maven:3.9.9'
            args '-v /root/.m2:/root/.m2'
        }
    stages {
        stage('Build') {
            steps {
                echo "$PATH"
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
